"""init_db

Revision ID: e250cacfa980
Revises: 37d3058b196f
Create Date: 2024-12-18 23:26:02.434915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e250cacfa980'
down_revision = '37d3058b196f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
