"""init_db

Revision ID: 37d3058b196f
Revises: 6e9e60aa80e7
Create Date: 2024-12-15 19:46:45.452881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37d3058b196f'
down_revision = '6e9e60aa80e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
